name: Semgrep OSS Test Rules

on:
  pull_request:
    branches:
    - master
  workflow_dispatch: {}
  push:
    branches:
    - master
env:
  SEMGREP_SEND_METRICS: "off" # Opt out of metrics

jobs:
  semgrep:
    name: semgrep-test-rules
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      - name: validate rules
        run: semgrep --validate --config rules/
      - name: test rules
        run: semgrep --test --test-ignore-todo